### ISSUE TITLE
Error on retrieving moduleitem - add-course-maintenance-log

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/add-course-maintenance-log#2]
```
position': moduleItem[0].position,
                                                  ^

TypeError: Cannot read property 'position' of undefined
    at canvas.get (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\add-course-maintenance-log\main.js:34:51)
    at paginate (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:41:13)
    at Object.callReturned [as callback] (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:220:9)
    at C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:2257:31
    at C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at updateRateLimit (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:115:17)
    at updateRateLimit (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:58:9)
    at Request.request [as _callback] (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:102:13)
    at Request.self.callback (C:\Users\Xacheiree\Desktop\Projects\d2l-to-canvas-conversion-tool\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
```

Occurred in the gauntlet.

**Comment by zachintosh** [comment]
Fixed
